### ISSUE TITLE
Gzip files not being used from cloudfront

### ISSUE THREAD

**Issue by radanskoric** [AssetSync/asset_sync#153]
Using the asset_sync gem with cloudfront the way it is described in the README will mean that gzip-ed versions of the assets will never be used. Rails will generate normal asset urls (ending in .js, .css, ...) , browser will request them with Accept-Encoding: gzip, ... and Cloudfront will just serve the uncompressed version of the file.

It can be seen when you monitor the traffic on your machine and it is explained in documentation here: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

For it to use the gziped versions, Rails app needs to be modified to generate asset urls with .gz version if the client supports gziped assets, but also asset_sync needs to set the Content-Type in S3 metadata of the gziped version to match the original file type (application/javascript, text/css, .. etc) instead of gzip file type.

Am I missing something? Can somebody confirm that they have gziped assets being served from cloudfront with app setup as decribed in asset_sync README?

It seems to me this is a big deal since in most cases downloading a gzipped version from origin will be faster than downloading ungzipped version from cdn edge location.

**Comment by betocols** [comment]
Hello @radanskoric 

I've been trying to implement your solution for serving gzipped files via Cloudfront. Nonetheless I've been getting this error once and again: "NameError: uninitialized constant Middleware" when trying to push to the Heroku repository.

I've put the file "compressed_static_assets.rb" in config/initializers folder and in the config/middleware folder, but it's always the same result.

Sorry for bringing this thread up after it's been closed for such a long time.

**Comment by radanskoric** [comment]
@betocols I don't think `config` is on the look up path for autoloading. It would probably work if you put it into `lib/middleware`, but in order to be completely sure I suggest you explicitly require the file at the top of your `production.rb`.
