### ISSUE TITLE
Expires header should not be set on assets

### ISSUE THREAD

**Issue by bdarfler** [AssetSync/asset_sync#252]
In the context of infrequently updated assets (one off images and the like).

When the asset is uploaded the expires header is set to one year in the future. However, if the asset is never changed then that expires header never changes either. A year later the expires header is now in the past. We currently have this issue with a number of images on our site that were uploaded in 2012 and now have a 2013 expires date.

Since the cache-control header is a relative value it does not have this issue and should be preferred. Of course cache-control is an http 1.1 header however it seems that many http 1.0 caches support it (http://www.mnot.net/blog/2007/05/15/expires_max-age).

I would suggest that either the Expires header be completely removed or that it at least be easily turned off. 

For now it can be currently overridden by setting Expires header to `nil` in the  `custom_headers`.

``` ruby
config.custom_headers = { '.*' => 
    { cache_control: 'public, max-age=31536000', expires: nil }
}
```

**Comment by gmcnaughton** [comment]
One saving grace (assuming you're using CloudFront as your CDN) is that when both "Expires" and "Cache-Control" headers are set, Cache-Control takes precedence.  From http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html:

> We recommend that you use the Cache-Control max-age directive instead of the Expires header field to control object caching. __If you specify values both for Cache-Control max-age and for Expires, CloudFront uses only the value of max-age.__

Other CDN and browser behavior may vary though!

**Comment by bdarfler** [comment]
Closing out my old issues.
