### ISSUE TITLE
assets are not copied to amazon bucket

### ISSUE THREAD

**Issue by hopewise** [AssetSync/asset_sync#262]
My bucket is pointed to using the CNAME: assets which used with my domain: myapp.com
so its assets.myapp.com

When I push my app to heroku and check the urls of assets I can see:

<link href="http://assets.myapp.com/assets/application-5ea496b2544e770dd32eddc798ebe844.css" media="all" rel="stylesheet" />

<script src="http://assets.myapp.com/assets/application-2020c3d1d37b4e77942c8d4b54d4b790.js"></script>

I have added the credentials details to my rails 4 app, but there isn't any file uploaded to the bucket, and its totally empty after pushing to heroku.

Any one can help?

**Comment by hopewise** [comment]
@ravzski can you please rename the domain name to assets.myapp.com for privacy, thanks :)
I've solved this issue long time ago!

**Comment by PikachuEXE** [comment]
@hopewise Edited
