### ISSUE TITLE
Custom headers needs documentation

### ISSUE THREAD

**Issue by bschaeffer** [AssetSync/asset_sync#289]
How do custom headers work? I've only ever seen examples in two issues (#232 & #233) that we're never really closed and have basically no discussion so they didn't help

For instance, I'm using Rackspace and would like to set some `Access-Control-*` headers on my font assets, here's my `custom_headers` configuration:

``` ruby
config.custom_headers = {
  '.*\.(ttf|otf|eot|woff|svg|swf)$' => {
    access_control_allow_origin: '*',
    access_control_max_age: 1728000,
  }
}
```

`.*\.(ttf|otf|eot|woff|svg|swf)$` looks like a pretty good regular expression to me, as all the examples I've seen seem to indicate that string/regex keys seem to be allowed.

But none of my font files are being uploaded, even after a `rake assets:clean assets:clobber` call.

**Comment by bschaeffer** [comment]
Okay, so my example was bad. Needed double quotes `"` instead of single quotes as a key. Still think there needs to be some documentation on that end.

**Comment by embs** [comment]
I agree about the documentation. I couldn't find, for instance, how to configure custom headers through environment variable. Is that possible?

**Comment by PikachuEXE** [comment]
I don't think there is a way to config it through environment variable
Since it's a hash of a hash
