### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by guyisra** [AssetSync/asset_sync#313]
Is this still being maintained? Lots of PRs with no merges..

Is it possible for someone to take over this?

**Comment by suan** [comment]
Hate to just leave a "+1", but hoping too that rumblelabs comes back or someone interested can take over.

**Comment by josacar** [comment]
@davidjrice any updates on this?

**Comment by gravesb** [comment]
See #316.

**Comment by Overload119** [comment]
We should close this one too. It's being maintained given the changelogs. 
https://changelogs.md/github/rumblelabs/asset_sync/
