### ISSUE TITLE
Asset sync invalid url is being constructed

### ISSUE THREAD

**Issue by sathishceg** [AssetSync/asset_sync#318]
Invalid url is being constructed with the setting **config.assets.prefix="abc/def"**.

If the current page url is https://sample.com/hello/new then the url for the assets in that page is being constructed as **domain/hello/abc/def** instead of **domain/abc/def** why is *hello* being added to the prefix in the asset url?

**Comment by PikachuEXE** [comment]
What do you use to get `domain/hello/abc/def`?
Using `image_tag`/`javascript_tag` in template?
