### ISSUE TITLE
File uploaded to S3 no longer sets expires & cache-control headers

### ISSUE THREAD

**Issue by mintuhouse** [AssetSync/asset_sync#320]
Sprockets now generates 64 byte digests & https://github.com/AssetSync/asset_sync/blob/master/lib/asset_sync/storage.rb#L140 causes it to fail

**Comment by PikachuEXE** [comment]
#315 is closed
Does that solve this issue?

**Comment by mintuhouse** [comment]
Haven't checked but since this is a duplicate of #315, you may close this
