### ISSUE TITLE
Every recent version of asset_sync has been released on August 26, 2013 on rubygems.org

### ISSUE THREAD

**Issue by sullerandras** [AssetSync/asset_sync#337]
It is quite confusing to look at the [asset_sync versions on rubygems.org](https://rubygems.org/gems/asset_sync/versions), because every release from 0.6.0 has a release date `August 26, 2013`:
```
47 VERSIONS SINCE JULY 30, 2011:
2.0.0 - August 26, 2013 (32 KB)
1.3.0 - August 26, 2013 (31.5 KB)
1.2.1 - August 26, 2013 (31.5 KB)
1.2.0 - August 26, 2013 (31.5 KB)
1.1.0 - August 26, 2013 (30.5 KB)
1.0.0 - August 26, 2013 (29.5 KB)
0.6.0 - August 26, 2013 (29.5 KB) yanked
0.5.4 - January 16, 2013 (25.5 KB)
0.5.3 - January 8, 2013 (25 KB)
```
Is it possible to correct these? Or at least update the release process so the new versions will be released with correct dates?

**Comment by PikachuEXE** [comment]
FIxed in 1855fa30d53546b79032a47b35c8fa70bc82f800
I didn't notice it until this issue
If you need accurate release date please see CHANGELOG or releases page (tags)
