### ISSUE TITLE
Rails 5.1 / webpacker support

### ISSUE THREAD

**Issue by davidbiehl** [AssetSync/asset_sync#344]
we upgraded to rails 5.1 and are using webpacker to build our react application. it doesn't appear that asset_sync is uploading any of the "packs" to s3. the existing asset pipeline (sprokets) js still gets uploaded just fine, but the pack files are missing.

**Comment by PikachuEXE** [comment]
Please see #346 to see if it suits your need

**Comment by PikachuEXE** [comment]
`2.2.0` released, please have a try

**Comment by davidbiehl** [comment]
awesome, thank you!
