### ISSUE TITLE
asset_sync and Rails 5.1.4

### ISSUE THREAD

**Issue by osahaidak** [AssetSync/asset_sync#359]
Hello, 
Is asset_sync works with Rails 5 correctly? I am not able to get AWS.
During to assets compilation I get "aws is not a recognized provider"

I have config like this:
[https://github.com/rotati/wiki/wiki/Setup-Staging-S3-buckets-and-install-asset-sync]

Any through?

**Comment by PikachuEXE** [comment]
If you are using 2.x
You need to require `fog-aws` yourself either in Gemfile or initializer
See https://github.com/AssetSync/asset_sync#installation

If you have done that already, please post your actual config

**Comment by osahaidak** [comment]
Yes, now looks like work fine with fog-aws. Thanks!
