### ISSUE TITLE
Do you follow SemVer? Can you mention it in README?

### ISSUE THREAD

**Issue by pravi** [AssetSync/asset_sync#368]
Even though I'd like SemVer to be the default its different in practice, so I ask for explicit confirmation and here is the responses so far https://wiki.debian.org/Teams/Ruby/UpstreamPledge

Currently gitlab wants asset_sync ~> 2.2.0 and I cannot update asset_sync in debian to 2.4.0 without patching gitlab. If you follow SemVer, I can ask gitlab to specify it as ~> 2.2 making it possible for me to update asset_sync in debian to new versions easily.

**Comment by PikachuEXE** [comment]
https://github.com/AssetSync/asset_sync/blob/master/CHANGELOG.md

```
All notable changes to this project will be documented in this file. This project adheres to Semantic Versioning.
```
