### ISSUE TITLE
Advice for performance at AWS CodeBuild?

### ISSUE THREAD

**Issue by hopewise** [AssetSync/asset_sync#405]
Hello

As pre-compilation takes about 20 minutes each time, is there any advice to minimize that time?
As we use AWS Codebuild, which uses a compute power to build the docker image, I tried the following:

- 7 GB memory, 4 vCPUs
- 15 GB memory, 8 vCPUs

but the building time was almost the same.

If there are any advice to gain more performance at building, that would be appreciated.

**Comment by PikachuEXE** [comment]
If it's about asset precompile, this gem won't do anything about it.
If you think it's about asset sync being slow, would be great to see some testing 
(like putting time used on sync vs precompile)

**Comment by hopewise** [comment]
I have just measured pre-compilation, its about 15 minutes, how to measure sync time?

**Comment by PikachuEXE** [comment]
By looking at
https://medium.com/@t2013anurag/rails-adding-global-hooks-for-rake-tasks-7faf0844364

I think (not tested) it would be something like
```
task :assets_sync_meature_before_hook
  @assets_sync_start_time = Time.current
end
task :assets_sync_meature_after_hook
  end_time = Time.current
  duration = end_time - @assets_sync_start_time
  puts "assets_sync Duration => #{duration}"
end
Rake::Task['assets:sync'].enhance [:assets_sync_meature_before_hook, :assets_sync_meature_before_hook]

```

**Comment by hopewise** [comment]
thanks, I will try that when I can
