### ISSUE TITLE
Support `google_json_key_string` as an alternative to `google_json_key_location`

### ISSUE THREAD

**Issue by nwallace** [AssetSync/asset_sync#407]
In some environments, (in my case, Kubernetes), it can be easier to store uncommitted secrets in the environment itself, rather than on disk. Fog itself supports being configured either way. I don't believe there's a reason this gem can't work the same way

**Comment by PikachuEXE** [comment]
Sorry I am on holiday
Come back next week

**Comment by PikachuEXE** [comment]
I think it's fine but you have to create the PR and test it (manually) 
Automatic test is also required like what's done for `GOOGLE_JSON_KEY_LOCATION`

**Comment by PikachuEXE** [comment]
Should be fixed via #415
