### ISSUE TITLE
Move away from TravisCI?

### ISSUE THREAD

**Issue by PikachuEXE** [AssetSync/asset_sync#409]
https://news.ycombinator.com/item?id=25338983
Maybe TravisCI still runs for this project but not sure for how long
Also many jobs are queued for long time and not run yet

GitHub Action is my go-to choice although there are things that it doesn't support yet
e.g. `allow-failures`, `ppc64le` support (#408)

@davidjrice What do you think?

**Comment by shmokmt** [comment]
@PikachuEXE 
It looks like TravisCI is no longer being used now.
How about delete `.travis.yml` and close this issue?

**Comment by PikachuEXE** [comment]
I forgot to remove it after I become collaborator...
Thx :P
https://github.com/AssetSync/asset_sync/commit/4a6500f436b9266b2453585e227cc9db533abbf0
