### ISSUE TITLE
Upload files from public/

### ISSUE THREAD

**Issue by Overload119** [AssetSync/asset_sync#421]
I have several files inside of my codebase `public/` and they are getting uploaded but not handled by Rails in production.
Other assets work fine.

For example:

- `public/manifest.json` exists locally.
- I see it in my DigitalOcean spaces under `/` root and not `/production/assets/manifest.json` as I would expect.
- website.com/manifest.json leads to a 404.

Here are some relevant configurations:

```rb
# production.rb
config.assets.compile = false
config.assets.prefix = '/production/assets'
config.assets.digest = true
config.action_controller.asset_host =
    'https://<mydomain>.nyc3.digitaloceanspaces.com/'
```

```rb
# asset_sync.rb
 config.add_local_file_paths do
      # Any code that returns paths of local asset files to be uploaded
      # Webpacker
      public_root = Rails.root.join('public')
      additional_paths =
        Dir.chdir(public_root) do
          packs_dir =
            Webpacker.config.public_output_path.relative_path_from(public_root)
          Dir[File.join(packs_dir, '/**/**')]
        end

      # images, videos, and root of Public
      additional_paths +=
        Dir.chdir(public_root) { Dir['*.{html,json,png,ico,txt,js}'] }
      additional_paths +=
        Dir.chdir(public_root) { Dir['images/*.{html,json,png,ico,txt,js}'] }
      additional_paths +=
        Dir.chdir(public_root) { Dir['videos/*.{html,json,png,ico,txt,js}'] }

      additional_paths
    end
```

Can anyone shed some light on this?

**Comment by PikachuEXE** [comment]
How do you upload asset files to `/production/assets`?

Also might worth inspecting `Dir.chdir(public_root) { Dir['*.{html,json,png,ico,txt,js}'] }` to see if it really includes `public/manifest.json`

**Comment by Overload119** [comment]
I ran `rake assets:sync`  and saw "Uploading... manifest.json"

I verified that it's on DigitalOcean Spaces as well.

![CleanShot 2021-09-15 at 20 50 14](https://user-images.githubusercontent.com/1012072/133546524-2ea7b044-163a-4b92-a708-ea88fa0bdb0f.png)

I believe ApplicationController is handling the 404 when I visit `/manifest.json` instead of sending the file above.
It works fine for other assets files, such as the ones in '/production/assets/'

**Comment by Overload119** [comment]
I tried another thing:

```
https://www.<mydomain>.com/production/assets/file-6810377927b5c809da7dc379201de718a32e886a97236aff1d5d5a92f5f90d8f.png
https://<mybucket>.nyc3.digitaloceanspaces.com/production/assets/file-6810377927b5c809da7dc379201de718a32e886a97236aff1d5d5a92f5f90d8f.png
```

I would expect both of these to work but the first does not while the second does.

**Comment by PikachuEXE** [comment]
`website.com/manifest.json leads to a 404`: 
That could be your config/controller issue

`I see it in my DigitalOcean spaces under / root and not /production/assets/manifest.json as I would expect.`:
Already answered above

I would question
1. Is the config setup correctly so that the asset files would be uploaded to `/production/assets` on DO Space
2. Is `public/manifest.json` part of the asset files to be uploaded

How to map `website.com/manifest.json` to DO Space `/production/assets/manifest.json` is your issue and not this project's issue.

**Comment by Overload119** [comment]
Yes, I don't think it was related to this gem.

In my case I found that my Docker image didn't contain the files that are required, such as `public/packs/manifest.json` - this is required for AssetSync to look up the assets on DigitalOcean.
