### ISSUE TITLE
config.existing_remote_files = 'delete' doesn't seem to work

### ISSUE THREAD

**Issue by manuelmeurer** [AssetSync/asset_sync#53]
I have the option set in my initializer but still my S3 folder is littered with old asset files.
On every deploy it says

```
 ** [out :: myapp.com] Fetching files to flag for delete
 ** [out :: myapp.com] Flagging 0 file(s) for deletion
```

What could be the cause?

**Comment by julienbfabre** [comment]
> False alarm.

what was the issue? i am also seeing the same behavior where i remove files but 0 files are flagged for deletion.
