### ISSUE TITLE
Is there a verbose option?

### ISSUE THREAD

**Issue by rymohr** [AssetSync/asset_sync#72]
It would be nice to see a summary of what happened during a `sync` operation but I didn't see anything in the config options.

Great library btw!

**Comment by skylarmb** [comment]
Sorry to dig up such an old thread, but if you are just looking for output for debugging purposes in development like me, simply prefixing with the `RAILS_GROUPS=assets` works fine. 

`RAILS_GROUPS=assets rake assets:sync`
