### ISSUE TITLE
S3 error: RequestTimeTooSkewed

### ISSUE THREAD

**Issue by drewda** [AssetSync/asset_sync#84]
I am trying to use Capistrano to precompile assets, but so far I'm just getting the following error. I have a lot of assets to precompile, so I can understand why the job takes a while to complete. But why should this delay be a problem with the S3 upload?

Any suggestions for how to debug or fix? Thanks in advance.
## 

 *\* [out :: questions.spatialability.org] response => #<Excon::Response:0xc972b68 @body="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>6EF1AA7356923B14</RequestId><HostId>34aW6+f/Kn1/4SkaOUbyVb9DLJyaefqKKcL89zDS9exchUoUKh5S7sUiHeTt3hnv</HostId><RequestTime>Mon, 18 Jun 2012 20:18:46 +0000</RequestTime><ServerTime>2012-06-18T20:02:18Z</ServerTime></Error>", @headers={"x-amz-request-id"=>"6EF1AA7356923B14", "x-amz-id-2"=>"34aW6+f/Kn1/4SkaOUbyVb9DLJyaefqKKcL89zDS9exchUoUKh5S7sUiHeTt3hnv", "Content-Type"=>"application/xml", "Transfer-Encoding"=>"chunked", "Date"=>"Mon, 18 Jun 2012 20:02:17 GMT", "Server"=>"AmazonS3"}, @status=403>

**Comment by sankalp-khare** [comment]
When you faced this, were you using IAM based instance privileges for EC2? or were you using a IAM user's credentials.
